# Generated by Django 3.0.7 on 2020-07-10 11:18

import accounts.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rank', models.PositiveSmallIntegerField()),
                ('last_modified', models.DateTimeField()),
                ('deadline', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('deadline_month', models.IntegerField()),
                ('deadline_year', models.IntegerField()),
                ('assigned_to', models.ForeignKey(default=accounts.models.Project_Member, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo_assigned_to', to='accounts.Project_Member')),
                ('last_modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_last_modified', to='accounts.Project_Member')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Project')),
            ],
        ),
    ]
