# Generated by Django 3.0.7 on 2020-06-23 05:16

import accounts.models
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_merge_20200616_1652'),
        ('todo', '0005_auto_20200614_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='assigned_to',
            field=models.ForeignKey(default=accounts.models.Project_Member, on_delete=django.db.models.deletion.CASCADE, related_name='todo_assigned_to', to='accounts.Project_Member'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='todo',
            name='rank',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='todo',
            name='todo',
            field=models.CharField(max_length=300),
        ),
    ]
